### ISSUE TITLE
some questions about code

### ISSUE THREAD

**Issue by xiaomingnio** [jiamingNo1/Temporal-Shift-Module#2]
1、mv2的预训练模型是在ImageNet上训练好的么？
2、我跑了一下，在jester上准确率是90%，在测试阶段为什么还要重新加载一下mobilenet_v2.pth.tar，那么特征提取这部分是不是要微调一下，不是很明白TSM是在MV2把特征提取好了再做后续工作，还是test的时候用TSM_jester_RGB_MobileNetV2_shift8_blockres_avg_segment8_e5.pth这个模型。

**Comment by xiaomingnio** [comment]
..

**Comment by jiamingNo1** [comment]
@xiaomingnio 
1、预训练模型是在ImageNet上训练好的，直接从官方链接下载的。
2、测试的时候加载的模型是训练过的最终模型，该模型是放在online_demo目录下的mobilenetv2_jester.pth.tar，tsm模块是在tsn网络的基础上改进添加的一个模块，对视频行为问题的分析和解决有帮助。

**Comment by xiaomingnio** [comment]
谢谢，已经跑通了，感觉这个数据集对主干网络要求不高，我用MV2_0.25也可以达到93%的准确率。

**Comment by jiamingNo1** [comment]
嗯嗯，多试试。

**Comment by zhunge** [comment]
> 谢谢，已经跑通了，感觉这个数据集对主干网络要求不高，我用MV2_0.25也可以达到93%的准确率。

mv2_0.25是这份代码跑的还是原作者代码跑出来的？我用这份代码跑出来不及格
