### ISSUE TITLE
Do you have the jester submit test results? which present in the Leaderboard?

### ISSUE THREAD

**Issue by zhangyuan1994511** [jiamingNo1/Temporal-Shift-Module#3]

**Comment by jiamingNo1** [comment]
@zhangyuan1994511 Yes, the 16th on the leaderboard is me. And because of the computing power of machine, the maximum value of batch size can be set as 16, if batch size can be set to 64, the test result can be better.

**Comment by zhangyuan1994511** [comment]
@jiamingNo1 Thank you for your reply! Could you provide the test model? My computer can set the batchsize at 64, I want use yours as pretrain model. Sure, I also provide my model for you after training.

**Comment by jiamingNo1** [comment]
@zhangyuan1994511 The model is on online_demo directory, and mobilenetv2_jester.pth.tar is the model. But I suggest you train from imagenet pretrained model, after all, the training time is only one or two days.

**Comment by zhangyuan1994511** [comment]
@jiamingNo1 OK, I ge it! Thank you very much!
